### ISSUE TITLE
Accessibility support for treebeard

### ISSUE THREAD

**Issue by lisaeatsworld** [storybookjs/react-treebeard#188]
We are using treebeard component for our UI, and it works great! Our UI needs to meet WCAG 2, but current version of treebeard doesn't provide any support for accessibility, such as `aria` attributes, `role`, etc.

Currently treebeard only supports some customization but not the sub-components that we need to add the aria attributes to. According to W3C document, these attributes, such as `aria-expanded` and `role`, need to be on the tree node, which contains the sub-nodes. However, the customization via decorator could only apply to the header row (toggle, header, or their container) of the subtree. So I can only add aria attributes on the header, but not the tree nodes.
 
Do you have any plan to add accessibility support? Thanks!

**Comment by maximilianoforlenza** [comment]
Hi @lisaeatsworld we don't have any plan to add accessibility support for now, anyway if you have any idea we expect your contribution.

Thanks!
