### ISSUE TITLE
can i add background-color to container when hover?

### ISSUE THREAD

**Issue by JayneYan98** [storybookjs/react-treebeard#217]

**Comment by maximilianoforlenza** [comment]
Hi @JayneYan98 at this moment is not possible, but I'm working in this.

**Comment by maximilianoforlenza** [comment]
@JayneYan98 this is my solution: https://codesandbox.io/s/heuristic-bird-mirnp I don't like but is working.

**Comment by maximilianoforlenza** [comment]
Please reopen issue if not working.
