### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop. 

### ISSUE THREAD

**Issue by MorganaUzhgorod** [storybookjs/react-treebeard#221]
I use TreeBeard as component.  Can anybody help please?

```
...      
import { Treebeard } from 'react-treebeard';
...
      <Treebeard
          data={data}
          onToggle={this.onToggle}
        />
```
Warning in my console:

![Снимок экрана 2019-06-18 в 18 19 39](https://user-images.githubusercontent.com/8722709/59697064-dea6d000-91f5-11e9-86fd-1231dcf5a531.png)

**Comment by maximilianoforlenza** [comment]
Hi @MorganaUzhgorod! Do you have an `id` attribute in data?
```
const data = {
id: 1,
name: 'something'
...
}
```

**Comment by MorganaUzhgorod** [comment]
@maximilianoforlenza  No, I do not have :( I receive this data (Files tree list) from backend

**Comment by maximilianoforlenza** [comment]
@MorganaUzhgorod It's the problem, because actually react-treebeard doesn't has a "default index"

**Comment by MorganaUzhgorod** [comment]
@maximilianoforlenza, ok, Thanks 🖖
I wrote temporary solution. Function that add id to each element of JSON, and it's work without warning for this time.
Thanks ✋

**Comment by maximilianoforlenza** [comment]
fix https://github.com/storybookjs/react-treebeard/pull/222

**Comment by leon0707** [comment]
I use 3.2.4

<img width="650" alt="Screen Shot 2019-10-11 at 11 16 47 AM" src="https://user-images.githubusercontent.com/523684/66663383-a39f3100-ec18-11e9-8c23-6e8857dc874e.png">

test folder in the children causes same problem. Both folders have id
