### ISSUE TITLE
Current example app is not working properly

### ISSUE THREAD

**Issue by metehansenol** [storybookjs/react-treebeard#223]
Hi Everyone,

First of all it's a great treeview implementation and I liked it a lot, but I realized there are a few problems in current source.

I tried current example app codes into a new react app and I noticed that active statutes of items and animations are doesn't work properly.

Then I cloned "react-treebeard" repo and built and run example app from original sources, but it's still doesn't work properly.

onToggle event that shows at readme file is wrong, I guess that's known issue but there are also any other problems like below;

- When I click any item after another one, active property of previous item I clicked still stuck true. 
- Animations isn't working properly like [this example app](http://storybookjs.github.io/react-treebeard)
- When I click root item it's always stuck active.

I think above issues occurs due to react or any other npm package version mismatch.

Any other one faced that problems ?

**Comment by maximilianoforlenza** [comment]
Hi, so you try this https://github.com/storybookjs/react-treebeard/pull/220?

**Comment by maximilianoforlenza** [comment]
hi @metehansenol https://codesandbox.io/s/treebeard-active-broke-lrkhb this is an example, how you should can close other tree when open new tree.

**Comment by metehansenol** [comment]
Thank you for your quick response @maximilianoforlenza. It helped me.
But anyway I noticed animations doesn't work when you have no item ids.
