### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by tsudodog** [storybookjs/react-treebeard#230]
Example throws an error because onToggle is not bound in the constructor. Add the following to the constructor like the pr [here](https://github.com/storybookjs/react-treebeard/pull/220) I'm not sure why it hasn't been merged since the build error is unrelated to a change in the README.md as far as I can tell. Seems like a harmless and easy change to help those less familiar with react who are interested in using this component. 

```
this.onToggle = this.onToggle.bind(this);
```

**Comment by maximilianoforlenza** [comment]
merged.

**Comment by tsudodog** [comment]
Awesome thanks!
