### ISSUE TITLE
[Question] Is it possible to expand node without selecting it?

### ISSUE THREAD

**Issue by mindaugasnakrosis** [storybookjs/react-treebeard#233]
Is it possible to expand a row without selecting it?

@maximilianoforlenza @cancerberoSgx @navarroaxel

**Comment by maximilianoforlenza** [comment]
Hi @mindaugasnakrosis! Do you want to expand the row when the mouse is hover on it?

**Comment by RokasVaitkevicius** [comment]
Current problems is that expand node and select it, are the same operations currently. Would it be possible to separate them? 

What I mean by that is only expanding the node, but not selecting it and other way around, clicking on it, selecting it, but not expanding/closing it.

Basically is it possible to do it like in this gif? This is done using another library.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17296899/64550006-a3bac100-d33a-11e9-8e10-e0c9553b701b.gif)

**Comment by maximilianoforlenza** [comment]
@RokasVaitkevicius what library is that?

**Comment by mindaugasnakrosis** [comment]
@maximilianoforlenza https://github.com/chenglou/react-treeview

But it is not maintained anymore, so difficult to use.

**Comment by mindaugasnakrosis** [comment]
We need the ability to:

- expand the node (one action)
- select the row (another action)

**Comment by maximilianoforlenza** [comment]
ok. Yes it is possible to does. I'll start to work on it.

**Comment by mindaugasnakrosis** [comment]
@maximilianoforlenza amazing! Looking forward to the changes.

**Comment by mindaugasnakrosis** [comment]
@maximilianoforlenza how is it going? Maybe you need some help?

**Comment by maximilianoforlenza** [comment]
hi @mindaugasnakrosis ! I've published a new release https://github.com/storybookjs/react-treebeard/releases/tag/v4.2.4-beta.0 this is a beta version.

Now you have a new prop called `onSelect` this prop send the node selected. Here is an example https://github.com/storybookjs/react-treebeard/blob/master/example/app.js and you have `customStyles` prop if you want to change the title color. 

please give me your feedback, if is ok I'll fix test and I'll publish stable version.

**Comment by mindaugasnakrosis** [comment]
At first glance everything looks amazing, we will investigate further and let you know our final feedback. 

Thanks a ton!

**Comment by mindaugasnakrosis** [comment]
@maximilianoforlenza everything is perfect! Thanks again, will be closing it now.

**Comment by maximilianoforlenza** [comment]
@mindaugasnakrosis Thanks! I'll fix the unit test and then I'll publish a new version (5.0.0).

**Comment by mhlmhl** [comment]
Is this new version published?  I have version 3.2.4 and onSelect doesn't work.  And I don't see onSelect in the ReadMe, either.

**Comment by RokasVaitkevicius** [comment]
If you want to have it, you have to use version "^4.2.4-beta.0". It has `onSelect` and `onToggle` separated and available. I don't know when it will be published and go out of beta.

**Comment by mhlmhl** [comment]
Thanks for the hint. It works well! (Correction of the previous version of this comment.)

I appreciate the new function.
